[tool.poetry]
name = "chatgpt-post-processing"
version = "0.1.0"
description = "A repository for post-processing my ChatGPT conversations"
authors = ["Louis-Guillaume Bossu <louis-guillaume.bossu@polytechnique.edu>"]
package-mode = false

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
ruff = "^0.6.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [[tool.poetry.source]]
# name = "pytorch-xpu-preview"
# url = "https://download.pytorch.org/whl/test/xpu"
# priority = "explicit"

[tool.poetry.dependencies]
python = "^3.12"

numpy = "*"

torch = { url = "https://download.pytorch.org/whl/test/xpu/torch-2.6.0%2Bxpu-cp312-cp312-linux_x86_64.whl"}
pytorch-triton-xpu = { url = "https://download.pytorch.org/whl/test/pytorch_triton_xpu-3.2.0-cp312-cp312-linux_x86_64.whl"}
triton = { url = "https://download.pytorch.org/whl/test/triton-3.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"}
torchvision = {url = "https://download.pytorch.org/whl/test/xpu/torchvision-0.21.0%2Bxpu-cp312-cp312-linux_x86_64.whl"}

transformers = "*"
accelerate = "*"
# datasets = "*"
tokenizers = "*"
# sentencepiece = "^0.1.99"
# protobuf = "*"
scipy = "*"

notebook = "*"
loguru = "*"
matplotlib = "*"
python-dotenv = "*"
huggingface-hub = "*"
# optimum = "^1.23.3"
# intel-extension-for-pytorch = "^2.5.0"
optimum-intel = "^1.21.0"
openvino = "^2024.6.0"
bitsandbytes = {url = "https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.44.1.dev0-py3-none-manylinux_2_24_x86_64.whl"}
dotenv = "^0.9.9"
chromadb = "^0.6.3"
opentelemetry-exporter-otlp-proto-grpc = "1.25.0"
graphviz = "^0.20.3"
scikit-learn = "^1.6.1"
scikit-image = "^0.25.2"


[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
strict = true
show_error_codes = true

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"]  # Enforce common error codes and flake8 rules
fix = true  # Automatically apply fixes for common issues (like import sorting or formatting)
